### NumPy:

1. Speed ==>> (Internally Optimized C and Fortran)
2. Functionality ==>> (Linear Algebra, Statistics, and other mathematical ops)
3. Library support ==>> (Pandas, Matplotlib, Scikit-learn, TensorFlow, and PyTorch)
4. Efficiency ==>> (Data Manipulation, Preprocessing, and Large Dataset)
5. Versatility =>> (Text, Tabuler, Image, Video, and Sound waves)
6. Community and resources ==>> (Tutorial, Guide, and Forums)

### From where I should start

* Arrays
* Array operations
* Indexing and Slicing
* Shape manipulation
* Math Function
* Linear algebra
* Broadcasting

### NumPy Arrays

In [1]:
!pip install numpy

In [2]:
import numpy as np

### Creating NumPy Array

In [6]:
arr_1d = np.array([1,2,3,4,5])

In [8]:
print(arr_1d)

[1 2 3 4 5]


In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


### Basic Operations

#### Array Size check

In [13]:
arr_1d.size

5

In [14]:
arr_2d.shape

(2, 3)

#### Accessing Elements

In [18]:
arr_1d[2]

3

In [22]:
arr_2d[1,1]

5

#### Slicing

In [26]:
arr_1d[1:4]

array([2, 3, 4])

In [31]:
arr_2d[0,1:]

array([2, 3])

#### Changing Elements

In [33]:
arr_1d[2] = 300

In [35]:
arr_1d

array([  1,   2, 300,   4,   5])

### Useful Functions

#### Zeros

In [38]:
zero = np.zeros((2,6))

In [39]:
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Ones

In [40]:
one = np.ones((3,9))

In [41]:
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Arange

In [42]:
rang = np.arange(11)
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Reshape

In [43]:
rang_2d = np.arange(6).reshape((2,3))

In [44]:
rang_2d

array([[0, 1, 2],
       [3, 4, 5]])